# Launch instances, runs some tasks
# and then terminate them

- name: Create a sandbox instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.micro
    security_group: default
    image: ami-db7b39e1
    vpc_subnet_id: subnet-7f67b91a
  tasks:
  - name: Launch instance
    ec2:
      group: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: true
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      assign_public_ip: yes
    register: ec2


# vim:ft=ansible:
